export const RECEIVE_REGISTRATIONS_USER = 'RECEIVE_REGISTRATIONS_USER';
export const RECEIVE_REGISTRATIONS_USERS_LIST =
  'RECEIVE_REGISTRATIONS_USERS_LIST';
export const REGISTRATION_METHOD = 'REGISTRATION_METHOD';
export const EDIT = 'EDIT';
