export const AUTHENTICATION = 'AUTHENTICATION';
export const LOGOUT = 'LOGOUT';
export const RECEIVE_REGISTRATIONS_USER = 'RECEIVE_REGISTRATIONS_USER';
export const RECEIVE_REGISTRATIONS_USERS_LIST =
  'RECEIVE_REGISTRATIONS_USERS_LIST';
export const DELETE_USERS_LIST = 'DELETE_USERS_LIST';
export const REGISTRATION_METHOD = 'REGISTRATION_METHOD';
export const EDIT = 'EDIT';
export const EDIT_CLEAN = 'EDIT_CLEAN';
export const EDIT_USER = 'EDIT_USER';
export const CHAT_ON = 'CHAT_ON';
export const CHAT_OFF = 'CHAT_OFF';
