export const RECEIVE_REGISTRATIONS_PERSONAL = 'RECEIVE_REGISTRATIONS_PERSONAL';
export const RECEIVE_REGISTRATIONS_CARD = 'RECEIVE_REGISTRATIONS_CARD';
export const REGISTRATION_METHOD = 'REGISTRATION_METHOD';
